/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as TenantRouteImport } from './routes/tenant'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantIndexRouteImport } from './routes/tenant.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TenantOrdersRouteImport } from './routes/tenant.orders'
import { Route as TenantMenusRouteImport } from './routes/tenant.menus'
import { Route as TenantEarningsRouteImport } from './routes/tenant.earnings'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'

const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantRoute = TenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIndexRoute = TenantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TenantOrdersRoute = TenantOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => TenantRoute,
} as any)
const TenantMenusRoute = TenantMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => TenantRoute,
} as any)
const TenantEarningsRoute = TenantEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => TenantRoute,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/tenant': typeof TenantRouteWithChildren
  '/track-order': typeof TrackOrderRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/tenant/earnings': typeof TenantEarningsRoute
  '/tenant/menus': typeof TenantMenusRoute
  '/tenant/orders': typeof TenantOrdersRoute
  '/admin/': typeof AdminIndexRoute
  '/tenant/': typeof TenantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/track-order': typeof TrackOrderRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/tenant/earnings': typeof TenantEarningsRoute
  '/tenant/menus': typeof TenantMenusRoute
  '/tenant/orders': typeof TenantOrdersRoute
  '/admin': typeof AdminIndexRoute
  '/tenant': typeof TenantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/tenant': typeof TenantRouteWithChildren
  '/track-order': typeof TrackOrderRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/tenant/earnings': typeof TenantEarningsRoute
  '/tenant/menus': typeof TenantMenusRoute
  '/tenant/orders': typeof TenantOrdersRoute
  '/admin/': typeof AdminIndexRoute
  '/tenant/': typeof TenantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/tenant'
    | '/track-order'
    | '/admin/orders'
    | '/admin/tenants'
    | '/tenant/earnings'
    | '/tenant/menus'
    | '/tenant/orders'
    | '/admin/'
    | '/tenant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/track-order'
    | '/admin/orders'
    | '/admin/tenants'
    | '/tenant/earnings'
    | '/tenant/menus'
    | '/tenant/orders'
    | '/admin'
    | '/tenant'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/tenant'
    | '/track-order'
    | '/admin/orders'
    | '/admin/tenants'
    | '/tenant/earnings'
    | '/tenant/menus'
    | '/tenant/orders'
    | '/admin/'
    | '/tenant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  TenantRoute: typeof TenantRouteWithChildren
  TrackOrderRoute: typeof TrackOrderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant': {
      id: '/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof TenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/': {
      id: '/tenant/'
      path: '/'
      fullPath: '/tenant/'
      preLoaderRoute: typeof TenantIndexRouteImport
      parentRoute: typeof TenantRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tenant/orders': {
      id: '/tenant/orders'
      path: '/orders'
      fullPath: '/tenant/orders'
      preLoaderRoute: typeof TenantOrdersRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/menus': {
      id: '/tenant/menus'
      path: '/menus'
      fullPath: '/tenant/menus'
      preLoaderRoute: typeof TenantMenusRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/earnings': {
      id: '/tenant/earnings'
      path: '/earnings'
      fullPath: '/tenant/earnings'
      preLoaderRoute: typeof TenantEarningsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrdersRoute: AdminOrdersRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TenantRouteChildren {
  TenantEarningsRoute: typeof TenantEarningsRoute
  TenantMenusRoute: typeof TenantMenusRoute
  TenantOrdersRoute: typeof TenantOrdersRoute
  TenantIndexRoute: typeof TenantIndexRoute
}

const TenantRouteChildren: TenantRouteChildren = {
  TenantEarningsRoute: TenantEarningsRoute,
  TenantMenusRoute: TenantMenusRoute,
  TenantOrdersRoute: TenantOrdersRoute,
  TenantIndexRoute: TenantIndexRoute,
}

const TenantRouteWithChildren =
  TenantRoute._addFileChildren(TenantRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  TenantRoute: TenantRouteWithChildren,
  TrackOrderRoute: TrackOrderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
